site_name: Docs Sample
site_url: https://ezabotkin.github.io/docs-sample-anon/
repo_url: https://github.com/EZabotkin/docs-sample-anon
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
        - locale: de
          name: Deutsch
          nav:
            - Startseite: index.md
            - Case Studies:
              - Case Studies: case-studies/enterprise/docs/index.md
              - Erste Schritte: case-studies/enterprise/docs/guides/getting-started.md
  - git-revision-date-localized:
      type: timeago            # формат: date|datetime|iso_*|timeago
      enable_creation_date: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - .
nav:
  - Home: index.md
  - Contributing: contributing/contributing.md
  - AI-Workflow Demo:
      - AI Transform Quickstart: ai/ai-transform.md
      - Preparing Input: workflow/preparing-input.md
      - HTTP Client: workflow/http-client.md
      - Post Process and Guardrails: workflow/post-process.md
      - Workflow Very Quick Start: workflow/quickstart.md
  - Metrics we watch: metrics/metrics.md
  - Troubleshooting: troubleshooting/troubleshooting.md
  - Case Studies:
      - Enterprise Platform (neutralized):
          - Introduction: case-studies/enterprise/docs/index.md
          - Guides:
              - Quickstart: case-studies/enterprise/docs/guides/quickstart.md
              - Getting Started: case-studies/enterprise/docs/guides/getting-started.md
              - Custom Alerts Feature: case-studies/enterprise/docs/guides/custom-alerts.md
          - References:
              - Users: case-studies/enterprise/docs/reference/users.md
