name: Link Check

on:
  pull_request:
    paths:
      - "docs/**"
      - "mkdocs.yaml"
      - "README.md"
      - "lychee.toml"
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (for MkDocs build)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site (MkDocs)
        run: |
          python -m mkdocs build --strict

      - name: Run Lychee (Markdown + built HTML)
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >
            --config lychee.toml
            --no-progress
            --verbose
            --format markdown
            --output ./lychee/out.md
            README.md
            docs/**/*.md
            site/**/*.html

          fail: false

      - name: Upload Lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: ./lychee/out.md
          if-no-files-found: ignore
